name: Cache Workflow

on: [push]

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-aa1ce0e

      - name: prime-cache-aa1ce0e
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi
